version: "3.8"

services:
  frontend:
    image: djmaldonado19/sie-frontend:${VERSION:-latest}
    container_name: sie_frontend
    restart: always
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development